"""added rss feed

Revision ID: 8ee6f41e9a93
Revises: 1ca82da5d433
Create Date: 2022-01-13 21:04:43.258084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee6f41e9a93'
down_revision = '1ca82da5d433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('is_rss', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search', 'is_rss')
    # ### end Alembic commands ###
