"""update FKs

Revision ID: dd9e0277e5e2
Revises: 4af027108f15
Create Date: 2021-11-14 13:46:22.224812

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'dd9e0277e5e2'
down_revision = '4af027108f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('search_location_search_id_fkey', 'search_location', type_='foreignkey')
    op.create_foreign_key(None, 'search_location', 'search', ['search_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('search_term_search_id_fkey', 'search_term', type_='foreignkey')
    op.create_foreign_key(None, 'search_term', 'search', ['search_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'search_term', type_='foreignkey')
    op.create_foreign_key('search_term_search_id_fkey', 'search_term', 'search', ['search_id'], ['id'])
    op.drop_constraint(None, 'search_location', type_='foreignkey')
    op.create_foreign_key('search_location_search_id_fkey', 'search_location', 'search', ['search_id'], ['id'])
    # ### end Alembic commands ###
